// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Whether this build targets staging. The staging TestFlight build passes
  /// `--dart-define=ANALYTICS_ENV=staging` (see ios-testflight.yml); production
  /// ships without it, so this is false for prod and local runs. Staging uses a
  /// separate Firebase iOS app (its own [iosStaging] appId) registered under the
  /// same `reacti-app` project, so push tokens are scoped to the
  /// `com.reacti.app.staging` bundle instead of production's.
  static const bool _isStaging =
      String.fromEnvironment('ANALYTICS_ENV') == 'staging';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return _isStaging ? iosStaging : ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD84LTSWjvsyXyoANjX0sWV2kIHXNCXFY',
    appId: '1:847921976144:android:e1673f16714ad909de1255',
    messagingSenderId: '847921976144',
    projectId: 'reacti-app',
    storageBucket: 'reacti-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6QxzyJCvydTS3OqkBtajlFtpjNGXSgXU',
    appId: '1:847921976144:ios:73368b3a5d5cbaa1de1255',
    messagingSenderId: '847921976144',
    projectId: 'reacti-app',
    storageBucket: 'reacti-app.firebasestorage.app',
    iosBundleId: 'com.reacti.app',
  );

  /// Staging iOS Firebase app — same `reacti-app` project, but a distinct app
  /// registered for the `com.reacti.app.staging` bundle (only [appId] and
  /// [iosBundleId] differ from [ios]). Selected on staging builds via
  /// [_isStaging] so the staging TestFlight app receives its own push tokens.
  static const FirebaseOptions iosStaging = FirebaseOptions(
    apiKey: 'AIzaSyB6QxzyJCvydTS3OqkBtajlFtpjNGXSgXU',
    appId: '1:847921976144:ios:ef23b40063f4878bde1255',
    messagingSenderId: '847921976144',
    projectId: 'reacti-app',
    storageBucket: 'reacti-app.firebasestorage.app',
    iosBundleId: 'com.reacti.app.staging',
  );
}
