// Reacti CI Dashboard — client-side renderer.
//
// Loads `data.json` (generated by the deploy-dashboard.yml workflow on
// every push) and renders four sections:
//
//   1. Status cards   — latest backend + flutter run, pass rate, avg duration
//   2. Pass/fail chart — bar per run, colored by conclusion
//   3. Duration chart — line per workflow, time on Y
//   4. Recent runs table — newest at top, clickable
//
// No backend, no auth, no API calls at render time — all data is
// baked into data.json at deploy time.

const REPO = "reacti25/reacti";
const REPO_URL = `https://github.com/${REPO}`;

const elBackendStatus = document.getElementById("backend-status");
const elBackendMetaDur = document.getElementById("backend-meta-duration");
const elBackendMetaWhen = document.getElementById("backend-meta-when");
const elBackendLink = document.getElementById("backend-link");

const elFlutterStatus = document.getElementById("flutter-status");
const elFlutterMetaDur = document.getElementById("flutter-meta-duration");
const elFlutterMetaWhen = document.getElementById("flutter-meta-when");
const elFlutterLink = document.getElementById("flutter-link");

const elPassRate = document.getElementById("pass-rate");
const elPassRateDetail = document.getElementById("pass-rate-detail");
const elAvgDuration = document.getElementById("avg-duration");
const elAvgDurationDetail = document.getElementById("avg-duration-detail");

const elLastUpdated = document.getElementById("last-updated");
const elRepoLink = document.getElementById("repo-link");
const elRunsTbody = document.querySelector("#runs-table tbody");

elRepoLink.href = REPO_URL;

/** Format a duration in seconds as "1m 23s" or "23s". */
function fmtDuration(seconds) {
  if (seconds == null || isNaN(seconds)) return "—";
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
}

/** Format an ISO date as "5 min ago" / "2 hours ago" / "Mar 12". */
function fmtRelative(iso) {
  if (!iso) return "";
  const date = new Date(iso);
  const diffMs = Date.now() - date.getTime();
  const diffSec = Math.floor(diffMs / 1000);
  if (diffSec < 60) return `${diffSec}s ago`;
  const diffMin = Math.floor(diffSec / 60);
  if (diffMin < 60) return `${diffMin} min ago`;
  const diffHr = Math.floor(diffMin / 60);
  if (diffHr < 24) return `${diffHr}h ago`;
  const diffDay = Math.floor(diffHr / 24);
  if (diffDay < 7) return `${diffDay}d ago`;
  return date.toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

/** Classify a run's conclusion into pass/fail/other for coloring. */
function classifyConclusion(c) {
  if (c === "success") return "pass";
  if (c === "failure") return "fail";
  return "other"; // cancelled, skipped, neutral, action_required, in_progress, null
}

function statusLabel(run) {
  if (run.status === "in_progress" || run.status === "queued") return "Running";
  switch (run.conclusion) {
    case "success": return "Passing";
    case "failure": return "Failing";
    case "cancelled": return "Cancelled";
    case "skipped": return "Skipped";
    default: return run.conclusion || run.status || "Unknown";
  }
}

async function loadData() {
  const resp = await fetch("data.json", { cache: "no-store" });
  if (!resp.ok) throw new Error(`data.json fetch failed: ${resp.status}`);
  return resp.json();
}

function renderHero(data) {
  if (data.generatedAt) {
    elLastUpdated.textContent = `Updated ${fmtRelative(data.generatedAt)}`;
  }

  const latestBackend = data.runs.find((r) => r.name === "Backend CI");
  const latestFlutter = data.runs.find((r) => r.name === "Flutter CI");

  function paintCard(run, statusEl, durEl, whenEl, linkEl) {
    if (!run) {
      statusEl.textContent = "no runs yet";
      statusEl.className = "status other";
      return;
    }
    const klass = classifyConclusion(run.conclusion);
    statusEl.textContent = statusLabel(run);
    statusEl.className = `status ${klass}`;
    durEl.textContent = `⏱ ${fmtDuration(run.durationSec)}`;
    whenEl.textContent = `· ${fmtRelative(run.updatedAt)}`;
    linkEl.href = run.url;
  }
  paintCard(latestBackend, elBackendStatus, elBackendMetaDur, elBackendMetaWhen, elBackendLink);
  paintCard(latestFlutter, elFlutterStatus, elFlutterMetaDur, elFlutterMetaWhen, elFlutterLink);

  // Pass rate over the entire set (across both workflows).
  const finished = data.runs.filter((r) => r.conclusion);
  const passed = finished.filter((r) => r.conclusion === "success").length;
  const total = finished.length;
  const pct = total > 0 ? Math.round((passed / total) * 100) : null;
  elPassRate.textContent = pct == null ? "—" : `${pct}%`;
  elPassRateDetail.textContent = total > 0 ? `${passed} of ${total} finished green` : "no finished runs yet";

  // Average duration (only over successful runs to avoid skew from cancels).
  const successDurations = data.runs
    .filter((r) => r.conclusion === "success" && r.durationSec)
    .map((r) => r.durationSec);
  const avg = successDurations.length
    ? successDurations.reduce((a, b) => a + b, 0) / successDurations.length
    : null;
  elAvgDuration.textContent = avg == null ? "—" : fmtDuration(avg);
  elAvgDurationDetail.textContent = avg == null
    ? "no successful runs yet"
    : `across ${successDurations.length} successful runs`;
}

function renderPassFailChart(data) {
  // Show last 30 runs, newest on the right (so a "left to right" reader
  // sees history flowing toward "now"). data.runs is newest-first, so
  // reverse it.
  const runs = data.runs.slice(0, 30).reverse();

  const labels = runs.map((r) => r.headSha?.slice(0, 7) || "");
  const values = runs.map(() => 1); // every bar the same height
  const colors = runs.map((r) => {
    const k = classifyConclusion(r.conclusion);
    if (k === "pass") return "#3fb950";
    if (k === "fail") return "#f85149";
    return "#6e7681";
  });

  new Chart(document.getElementById("chart-passfail"), {
    type: "bar",
    data: {
      labels,
      datasets: [{
        data: values,
        backgroundColor: colors,
        borderWidth: 0,
      }],
    },
    options: {
      maintainAspectRatio: false,
      plugins: {
        legend: { display: false },
        tooltip: {
          callbacks: {
            title: (items) => {
              const r = runs[items[0].dataIndex];
              return `${r.name} · ${statusLabel(r)}`;
            },
            label: (item) => {
              const r = runs[item.dataIndex];
              return [
                `Commit: ${r.headSha?.slice(0, 7) || ""} — ${r.displayTitle || ""}`,
                `Branch: ${r.headBranch || ""}`,
                `Duration: ${fmtDuration(r.durationSec)}`,
                `When: ${fmtRelative(r.updatedAt)}`,
              ];
            },
          },
        },
      },
      scales: {
        y: { display: false, max: 1 },
        x: { ticks: { display: false }, grid: { display: false } },
      },
    },
  });
}

function renderDurationChart(data) {
  const backend = data.runs.filter((r) => r.name === "Backend CI").slice(0, 30).reverse();
  const flutter = data.runs.filter((r) => r.name === "Flutter CI").slice(0, 30).reverse();

  // Use sequential indices so the two series share the X axis even if
  // they have different run counts.
  const maxLen = Math.max(backend.length, flutter.length);
  const labels = Array.from({ length: maxLen }, (_, i) => `#${maxLen - i}`).reverse();

  const backendData = labels.map((_, i) => backend[i]?.durationSec ?? null);
  const flutterData = labels.map((_, i) => flutter[i]?.durationSec ?? null);

  new Chart(document.getElementById("chart-duration"), {
    type: "line",
    data: {
      labels,
      datasets: [
        {
          label: "Backend CI",
          data: backendData,
          borderColor: "#58a6ff",
          backgroundColor: "rgba(88, 166, 255, 0.1)",
          tension: 0.2,
          spanGaps: true,
        },
        {
          label: "Flutter CI",
          data: flutterData,
          borderColor: "#d29922",
          backgroundColor: "rgba(210, 153, 34, 0.1)",
          tension: 0.2,
          spanGaps: true,
        },
      ],
    },
    options: {
      maintainAspectRatio: false,
      plugins: {
        legend: { labels: { color: "#c9d1d9" } },
        tooltip: {
          callbacks: {
            label: (item) => `${item.dataset.label}: ${fmtDuration(item.parsed.y)}`,
          },
        },
      },
      scales: {
        y: {
          beginAtZero: true,
          ticks: {
            color: "#8b949e",
            callback: (v) => fmtDuration(v),
          },
          grid: { color: "#21262d" },
        },
        x: {
          ticks: { color: "#8b949e" },
          grid: { color: "#21262d" },
        },
      },
    },
  });
}

function renderRunsTable(data) {
  const rows = data.runs.slice(0, 15).map((r) => {
    const klass = classifyConclusion(r.conclusion);
    const dotClass = r.status === "in_progress" || r.status === "queued"
      ? "running"
      : klass;
    return `
      <tr data-url="${r.url}">
        <td><span class="status-dot ${dotClass}"></span>${statusLabel(r)}</td>
        <td>${r.name}</td>
        <td>${r.headBranch || ""}</td>
        <td>
          <span class="commit-sha">${(r.headSha || "").slice(0, 7)}</span>
          <span class="commit-msg" title="${(r.displayTitle || "").replaceAll('"', '&quot;')}">${r.displayTitle || ""}</span>
        </td>
        <td>${fmtDuration(r.durationSec)}</td>
        <td>${fmtRelative(r.updatedAt)}</td>
      </tr>
    `;
  });
  elRunsTbody.innerHTML = rows.join("") || `<tr><td colspan="6">No runs yet.</td></tr>`;

  // Whole row clickable → open the run in a new tab.
  elRunsTbody.querySelectorAll("tr[data-url]").forEach((tr) => {
    tr.addEventListener("click", () => window.open(tr.dataset.url, "_blank"));
  });
}

async function main() {
  try {
    const data = await loadData();
    renderHero(data);
    renderPassFailChart(data);
    renderDurationChart(data);
    renderRunsTable(data);
  } catch (e) {
    elRunsTbody.innerHTML = `<tr><td colspan="6">Failed to load dashboard data: ${e.message}</td></tr>`;
    console.error(e);
  }
}

main();
